### ISSUE TITLE
add a comment header in mif file with a few lines of metadata (if mif is produced on the cluster)

### ISSUE THREAD

**Issue by cchrisgong** [pik-piam/magclass#101]
* the idea is to be able to link a mif file to a specific run path on the cluster, so when mif is created the run path is automatically written to a comment header after #
* R has a function to skip hash comment line: https://stackoverflow.com/questions/28433328/skip-comment-line-in-csv-file-using-r
it just needs to be made compatible with e.g. "read.report" type of magclass functions (or similar quitte function)
* Besides the run path, it would also be nice to include library version and model version from the reporting and run, and maybe a pointer to file name indicating the existence of a reporting documentation (if there is one in the future)

**Comment by Loisel** [comment]
:+1:

**Comment by tscheypidi** [comment]
The reporting format currently does not support comments. Introducing it in read.report and write.report would be rather straightforwards, but as these are not the only functions reading/writing these files, it might break workflows somewhere else. Therefor, I suggest not to add this feature here.
