### ISSUE TITLE
Selective magpie_expand

### ISSUE THREAD

**Issue by dklein-pik** [pik-piam/magclass#47]
Example:

`new.magpie(c("AFR.1","AFR.2","EUR.3"),fill = 1) + new.magpie(c("AFR","EUR"),fill = 1)`

```
Error in new.magpie(c("AFR.1", "AFR.2", "EUR.1"), fill = 1) + new.magpie(c("AFR",  : 
  MAgPIE objects after MAgPIE object expansion do not agree in dimnames! magpie_expand seems to be bugged!
 e1:NA
 e2:EUR.2
In addition: Warning messages:
1: In unlist(dimnames(e1)) != unlist(dimnames(e2)) :
  longer object length is not a multiple of shorter object length
2: In unlist(dimnames(e1)) != unlist(dimnames(e2)) :
  longer object length is not a multiple of shorter object length
3: In unlist(dimnames(e1)) != unlist(dimnames(e2)) :
  longer object length is not a multiple of shorter object length
```

magpie_expand is not able to detect for which combinations of entries from different dimensions it should expand a magclass object before using it for calculation. Currently this could only be solved by performing a full expansion to all possible combinations.

**Comment by tscheypidi** [comment]
fixed with revision a68d0ff52d84d78e2d3f5999a4b131c861fc01c5
