### ISSUE TITLE
Metadata change stop to warning?

### ISSUE THREAD

**Issue by bodirsky** [pik-piam/magclass#58]
When the metadata is activated, hardly any script runs anymore.
To "softly" switch over to the use of metadata, it would be nice to get warnings instead of stops.
Or to have a setting "onlywarning".
Then, when possible, one could already adopt this new feature, making the final transiton easier.

**Comment by tscheypidi** [comment]
As metadata calculations in magclass anyway need a major overhaul before they can be used productively I would like to close this issue for the moment. It will be tackled as soon as we have time to prepare metadata handling for productive use
