### ISSUE TITLE
Add a function that reorders data in magclass objects

### ISSUE THREAD

**Issue by giannou** [pik-piam/magclass#69]

**Comment by tscheypidi** [comment]
can you please elaborate a bit more what you mean with that? Something like `magpiesort`?

**Comment by giannou** [comment]
> Something like `magpiesort`?

Not quite, it was something we discussed off-line: changing the order of sub-dimensions in the data dimension (I think). I had a script that does this and the idea was to make a function out of it.

**Comment by tscheypidi** [comment]
`dimOrder` does that job
